import type { FinderItem, FinderLocation } from './finderTypes';

export const FINDER_ITEMS: FinderItem[] = [
  {
    id: 'desktop',
    name: 'Desktop',
    kind: 'folder',
    parentId: null,
    modifiedAt: '2026-07-25 09:14',
    sizeLabel: '7 items',
    summary: 'Pinned shortcuts, active handoff notes, and the latest working set.',
    preview: 'The Desktop stays intentionally clean: only active work, capture notes, and handoff packages remain visible.',
    tags: ['priority'],
  },
  {
    id: 'documents',
    name: 'Documents',
    kind: 'folder',
    parentId: null,
    modifiedAt: '2026-07-25 08:42',
    sizeLabel: '12 items',
    summary: 'Specs, proposals, and retained operating runbooks.',
    preview: 'Documents collects durable planning artifacts, decisions, and reference decks that are still in circulation.',
    tags: ['projects'],
  },
  {
    id: 'downloads',
    name: 'Downloads',
    kind: 'folder',
    parentId: null,
    modifiedAt: '2026-07-24 21:07',
    sizeLabel: '9 items',
    summary: 'Incoming assets waiting to be reviewed or promoted elsewhere.',
    preview: 'Downloads is treated as a staging buffer: raw captures, trial exports, and untriaged files live here briefly.',
    tags: ['shared'],
  },
  {
    id: 'applications',
    name: 'Applications',
    kind: 'folder',
    parentId: null,
    modifiedAt: '2026-07-22 15:18',
    sizeLabel: '5 items',
    summary: 'Installed tools and launchable bundles used during demos.',
    preview: 'Applications contains a curated set of launchable utilities and demo agents prepared for user testing.',
    tags: ['shared'],
  },
  {
    id: 'shared-drive',
    name: 'Shared Drive',
    kind: 'folder',
    parentId: null,
    modifiedAt: '2026-07-25 07:56',
    sizeLabel: '6 items',
    summary: 'Cross-functional handoff assets, briefs, and review snapshots.',
    preview: 'Shared Drive keeps cross-team deliverables close at hand, including approvals, exports, and async review packages.',
    tags: ['shared'],
  },
  {
    id: 'archive',
    name: 'Archive',
    kind: 'folder',
    parentId: null,
    modifiedAt: '2026-07-19 12:10',
    sizeLabel: '4 items',
    summary: 'Completed work moved out of the active workspace.',
    preview: 'Archive stores finalized milestones, cold backups, and content retained for traceability rather than daily use.',
    tags: ['shared'],
  },
  {
    id: 'handoff-packet',
    name: 'Handoff Packet',
    kind: 'folder',
    parentId: 'desktop',
    modifiedAt: '2026-07-25 09:14',
    sizeLabel: '3 items',
    summary: 'Delivery bundle prepared for the morning stakeholder walkthrough.',
    preview: 'A compact delivery packet: screenshots, summary notes, and a ready-to-share receipt log for the next review.',
    tags: ['priority', 'shared'],
  },
  {
    id: 'release-checklist',
    name: 'Release Checklist.md',
    kind: 'document',
    parentId: 'desktop',
    modifiedAt: '2026-07-25 08:51',
    sizeLabel: '14 KB',
    summary: 'Launch-day checklist for the demo environment and fallback plan.',
    preview: 'Confirm install path, verify approval receipts, capture 1024x768 screenshots, and re-run the browser smoke path before handoff.',
    tags: ['priority'],
  },
  {
    id: 'hero-concept',
    name: 'Hero Concept.png',
    kind: 'image',
    parentId: 'desktop',
    modifiedAt: '2026-07-24 20:16',
    sizeLabel: '4.8 MB',
    summary: 'Exploratory hero composition for the operating environment landing screen.',
    preview: 'Layered light panels with low-noise gradients and three focal clusters for Workbench, Store, and Approval states.',
    tags: ['projects'],
  },
  {
    id: 'daily-brief',
    name: 'Daily Brief.note',
    kind: 'note',
    parentId: 'desktop',
    modifiedAt: '2026-07-25 07:33',
    sizeLabel: '5 KB',
    summary: 'Quick operating notes pinned for the current work session.',
    preview: 'Keep Finder responsive, keep Calculator deterministic, and do not leak mock implementation details into user-facing labels.',
    tags: ['priority'],
  },
  {
    id: 'deck',
    name: 'Q3 Narrative Deck.key',
    kind: 'document',
    parentId: 'documents',
    modifiedAt: '2026-07-24 18:02',
    sizeLabel: '19 MB',
    summary: 'Narrative deck covering product framing, differentiators, and launch proof points.',
    preview: 'Slides 7-12 refine the argument that missions, approvals, and receipts form the durable operating model.',
    tags: ['projects'],
  },
  {
    id: 'briefing',
    name: 'Strategy Brief.pdf',
    kind: 'document',
    parentId: 'documents',
    modifiedAt: '2026-07-22 09:44',
    sizeLabel: '2.3 MB',
    summary: 'Decision brief aligning product narrative with operating constraints.',
    preview: 'The brief emphasizes durable task state, visible governance, and a trust boundary the agent surface cannot impersonate.',
    tags: ['projects', 'shared'],
  },
  {
    id: 'meeting-audio',
    name: 'Stakeholder Recap.m4a',
    kind: 'audio',
    parentId: 'documents',
    modifiedAt: '2026-07-20 14:18',
    sizeLabel: '28 MB',
    summary: 'Audio summary from the last design and architecture review.',
    preview: 'Timestamp 03:12 covers the approval digest language; 07:41 captures the ask for a clearer artifact lineage view.',
    tags: ['shared'],
  },
  {
    id: 'visuals',
    name: 'Visual System',
    kind: 'folder',
    parentId: 'documents',
    modifiedAt: '2026-07-23 16:28',
    sizeLabel: '4 items',
    summary: 'Reusable visual references and direction-setting compositions.',
    preview: 'A focused visual kit: gradients, icon studies, contrast checks, and desktop surface captures.',
    tags: ['projects'],
  },
  {
    id: 'gradient-study',
    name: 'Gradient Study.jpg',
    kind: 'image',
    parentId: 'visuals',
    modifiedAt: '2026-07-23 16:11',
    sizeLabel: '6.2 MB',
    summary: 'Color study for glass surfaces and ambient desktop lighting.',
    preview: 'Warm amber highlights balance the cooler navigation chrome to keep utility screens from feeling sterile.',
    tags: ['projects'],
  },
  {
    id: 'icon-board',
    name: 'Icon Board.sketch',
    kind: 'document',
    parentId: 'visuals',
    modifiedAt: '2026-07-22 11:54',
    sizeLabel: '8.6 MB',
    summary: 'Vector board with icon refinements for Finder, Calculator, and Mission states.',
    preview: 'Rounded geometry stays consistent across app metaphors while preserving enough contrast to remain legible at dock scale.',
    tags: ['projects'],
  },
  {
    id: 'capture-approval',
    name: 'trusted-approval.png',
    kind: 'image',
    parentId: 'downloads',
    modifiedAt: '2026-07-24 21:07',
    sizeLabel: '1.9 MB',
    summary: 'Screenshot capture of the approval sheet transition.',
    preview: 'Useful for comparing the system-owned chrome against the agent surface during final review.',
    tags: ['shared'],
  },
  {
    id: 'capture-store',
    name: 'agent-store.png',
    kind: 'image',
    parentId: 'downloads',
    modifiedAt: '2026-07-24 20:57',
    sizeLabel: '2.2 MB',
    summary: 'Store discovery screen used for release notes and demo proof.',
    preview: 'The featured card, search, and installation state all need to remain visible in the same viewport.',
    tags: ['shared'],
  },
  {
    id: 'receipt-export',
    name: 'receipt-log.csv',
    kind: 'document',
    parentId: 'downloads',
    modifiedAt: '2026-07-24 19:41',
    sizeLabel: '24 KB',
    summary: 'CSV export of approval receipts for validation and handoff.',
    preview: 'Rows include digest, effect key, principal, result, and the replay-safe timestamp used during the demo.',
    tags: ['priority', 'shared'],
  },
  {
    id: 'finder-app',
    name: 'Finder',
    kind: 'app',
    parentId: 'applications',
    modifiedAt: '2026-07-22 15:18',
    sizeLabel: 'Application',
    summary: 'Navigation shell for workspace browsing, search, and preview.',
    preview: 'Finder focuses on fast scope changes, confident selection, and a clear preview surface without modal context switches.',
    tags: ['shared'],
  },
  {
    id: 'calculator-app',
    name: 'Calculator',
    kind: 'app',
    parentId: 'applications',
    modifiedAt: '2026-07-22 15:18',
    sizeLabel: 'Application',
    summary: 'Calculation utility with history, keyboard input, and persistent context.',
    preview: 'The calculator handles chained arithmetic, percentage transforms, and recovery from invalid divide operations.',
    tags: ['shared'],
  },
  {
    id: 'agent-blueprint',
    name: 'Agent Blueprint.pdf',
    kind: 'document',
    parentId: 'shared-drive',
    modifiedAt: '2026-07-25 07:56',
    sizeLabel: '3.1 MB',
    summary: 'Cross-team architecture blueprint for the agent operating environment.',
    preview: 'This blueprint captures the contract boundaries between the store, mission runtime, approval plane, and artifact layer.',
    tags: ['projects', 'shared'],
  },
  {
    id: 'ops-video',
    name: 'ops-walkthrough.mov',
    kind: 'video',
    parentId: 'shared-drive',
    modifiedAt: '2026-07-23 19:20',
    sizeLabel: '86 MB',
    summary: 'Recorded walkthrough of the latest operator flow and recovery states.',
    preview: 'The most important segment demonstrates how the agent surface pauses cleanly before the trusted approval boundary.',
    tags: ['shared'],
  },
  {
    id: 'risk-log',
    name: 'risk-log.zip',
    kind: 'archive',
    parentId: 'archive',
    modifiedAt: '2026-07-19 12:10',
    sizeLabel: '12 MB',
    summary: 'Archived decision logs and supporting material from previous milestone reviews.',
    preview: 'Retained for traceability: older evidence packs, dependency evaluations, and timeline snapshots.',
    tags: ['shared'],
  },
];

export const FINDER_LOCATIONS: FinderLocation[] = [
  {
    id: 'recents',
    label: 'Recents',
    description: 'Recently modified files across the workspace.',
    kind: 'smart',
    section: 'favorites',
    icon: 'history',
  },
  {
    id: 'desktop',
    label: 'Desktop',
    description: 'Shortcuts and active work.',
    kind: 'folder',
    section: 'favorites',
    icon: 'monitor',
    rootId: 'desktop',
  },
  {
    id: 'documents',
    label: 'Documents',
    description: 'Specs, plans, and references.',
    kind: 'folder',
    section: 'favorites',
    icon: 'folder-open',
    rootId: 'documents',
  },
  {
    id: 'downloads',
    label: 'Downloads',
    description: 'Incoming assets and exports.',
    kind: 'folder',
    section: 'favorites',
    icon: 'download',
    rootId: 'downloads',
  },
  {
    id: 'applications',
    label: 'Applications',
    description: 'Installed tools and bundles.',
    kind: 'folder',
    section: 'favorites',
    icon: 'grid-2x2',
    rootId: 'applications',
  },
  {
    id: 'shared-drive',
    label: 'Shared Drive',
    description: 'Cross-team assets and reviews.',
    kind: 'folder',
    section: 'locations',
    icon: 'users',
    rootId: 'shared-drive',
  },
  {
    id: 'archive',
    label: 'Archive',
    description: 'Completed or cold storage material.',
    kind: 'folder',
    section: 'locations',
    icon: 'archive',
    rootId: 'archive',
  },
  {
    id: 'priority-tag',
    label: 'Priority',
    description: 'Files tagged for the current push.',
    kind: 'tag',
    section: 'tags',
    icon: 'tag-priority',
    tag: 'priority',
  },
  {
    id: 'projects-tag',
    label: 'Projects',
    description: 'Active product and design work.',
    kind: 'tag',
    section: 'tags',
    icon: 'tag-projects',
    tag: 'projects',
  },
  {
    id: 'shared-tag',
    label: 'Shared',
    description: 'Files prepared for collaboration or handoff.',
    kind: 'tag',
    section: 'tags',
    icon: 'tag-shared',
    tag: 'shared',
  },
];
